// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WeeklyDiet.Api.Data;

#nullable disable

namespace WeeklyDiet.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WeeklyDiet.Api.Models.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AllowedMealTypes")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("WeeklyDiet.Api.Models.FoodIngredient", b =>
                {
                    b.Property<int>("FoodId")
                        .HasColumnType("integer");

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer");

                    b.HasKey("FoodId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("FoodIngredients");
                });

            modelBuilder.Entity("WeeklyDiet.Api.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("WeeklyDiet.Api.Models.MealEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BaseFoodId")
                        .HasColumnType("integer");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<int>("FoodId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsLeftover")
                        .HasColumnType("boolean");

                    b.Property<int?>("LeftoverFromMealEntryId")
                        .HasColumnType("integer");

                    b.Property<int?>("ManualFoodId")
                        .HasColumnType("integer");

                    b.Property<int>("MealType")
                        .HasColumnType("integer");

                    b.Property<int>("WeeklyPlanId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BaseFoodId");

                    b.HasIndex("FoodId");

                    b.HasIndex("LeftoverFromMealEntryId");

                    b.HasIndex("ManualFoodId");

                    b.HasIndex("WeeklyPlanId", "DayOfWeek", "MealType")
                        .IsUnique();

                    b.ToTable("MealEntries");
                });

            modelBuilder.Entity("WeeklyDiet.Api.Models.WeeklyPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("WeekNumber")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Year", "WeekNumber")
                        .IsUnique();

                    b.ToTable("WeeklyPlans");
                });

            modelBuilder.Entity("WeeklyDiet.Api.Models.FoodIngredient", b =>
                {
                    b.HasOne("WeeklyDiet.Api.Models.Food", "Food")
                        .WithMany("Ingredients")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeeklyDiet.Api.Models.Ingredient", "Ingredient")
                        .WithMany("Foods")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("WeeklyDiet.Api.Models.MealEntry", b =>
                {
                    b.HasOne("WeeklyDiet.Api.Models.Food", "BaseFood")
                        .WithMany()
                        .HasForeignKey("BaseFoodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WeeklyDiet.Api.Models.Food", "Food")
                        .WithMany("Meals")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WeeklyDiet.Api.Models.MealEntry", "LeftoverFromMealEntry")
                        .WithMany()
                        .HasForeignKey("LeftoverFromMealEntryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WeeklyDiet.Api.Models.Food", "ManualFood")
                        .WithMany()
                        .HasForeignKey("ManualFoodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WeeklyDiet.Api.Models.WeeklyPlan", "WeeklyPlan")
                        .WithMany("Meals")
                        .HasForeignKey("WeeklyPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseFood");

                    b.Navigation("Food");

                    b.Navigation("LeftoverFromMealEntry");

                    b.Navigation("ManualFood");

                    b.Navigation("WeeklyPlan");
                });

            modelBuilder.Entity("WeeklyDiet.Api.Models.Food", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("Meals");
                });

            modelBuilder.Entity("WeeklyDiet.Api.Models.Ingredient", b =>
                {
                    b.Navigation("Foods");
                });

            modelBuilder.Entity("WeeklyDiet.Api.Models.WeeklyPlan", b =>
                {
                    b.Navigation("Meals");
                });
#pragma warning restore 612, 618
        }
    }
}
